name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Build zip
      #   id: build
      #   uses: thedoctor0/zip-release@0.7.6
      #   with:
      #     type: 'zip'
      #     filename: 'release.zip'
      #     exclusions: '*.git* /.github/**/*'

      - name: Zip Folder
        run: zip -r ${{ github.event.repository.name }}.zip . -x "*.git*" ".github/*"

      - name: Get commits since version
        id: commits
        run: echo "value=$(git log "$(git describe --tags --abbrev=0)..HEAD" --no-merges --oneline)" >> $GITHUB_STATE
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          body: |
            ${{ steps.commits.outputs.value }}
          files: ${{ github.event.repository.name }}.zip
